# 音乐存放目录
music_directory    "~/Music"

# 持久化数据目录(XDG_DATA_HOME)
playlist_directory "~/.local/share/mpd/playlists"
db_file            "~/.local/share/mpd/database"

# 状态与日志(XDG_STATE_HOME)
state_file         "~/.local/state/mpd/state"
log_file           "~/.local/state/mpd/log"

# 运行时PID(XDG_RUNTIME_DIR)
pid_file "/run/user/1000/pid"

# 歌曲贴纸/元数据
sticker_file       "~/.local/share/mpd/sticker.sql"

# 基础运行参数
bind_to_address    "127.0.0.1"
port               "6600"
auto_update        "yes"
auto_update_depth  "4"
log_level          "default"
restore_paused     "yes"

# 4. 音频输出（对接 PipeWire / PulseAudio）
audio_output {
    type            "pulse"
    name            "PipeWire Sound Server"
}

# 5. 音频流输出（供 ncmpcpp 渲染音频频谱图）
audio_output {
    type            "fifo"
    name            "Visualizer feed"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}
